---
apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: graviteeio
spec:
  ports:
  - port: 9200
    name: api
  selector:
    app: es

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-pvc
  namespace: graviteeio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  namespace: graviteeio
spec:
  selector:
    matchLabels:
      app: es
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - image: medinvention/elastic:7.5.1
          imagePullPolicy: IfNotPresent
          name: es
          resources:
            requests:
              memory: "0"
              cpu: "0"
          env:
            - name: discovery.type
              value: roundcubesingle-node
          ports:
            - containerPort: 9200
              name: api
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data-pvc