---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: graviteeio
spec:
  ports:
  - port: 27017
  selector:
    app: mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: graviteeio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: graviteeio
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: medinvention/mongodb:3.2.10
          imagePullPolicy: IfNotPresent
          name: mongo
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 27017
              name: tcp
          volumeMounts:
            - name: mongo-data
              mountPath: /var/lib/mongodb
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data-pvc